# Welcome to Jekyll!

# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Scuba Club at Virginia Tech
description: |
  Site is still under construction.
owner:
  name: Scuba Club at Virginia Tech
  email: scubaclub@vt.edu
  url: scubavt.github.io
first_published: 1965 # if migrating another site, the year of your first publish
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://arkadianriver.com" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Welcome!
  text: |
    "We dive not to escape life, but for life not to escape us."

    Welcome to the Scuba Club at Virginia Tech.

    The Scuba Club at Virginia Tech plans diving and non-diving events,
    hosts bi-weekly meetings for business and special speakers/presentations/topics,
    and provides training for scuba divers.

    Courses range from Discover Scuba (no experience required) to the Divemaster/Scuba Instructor course.
    You can even elect to become certified in technical skills such as Full-Cave, Trimix, and Closed Circuit Rebreather.
    
    We are working on this site to better facilitate the clubs mission, please stay tuned for updates to this site.

# - title for your blog's featured posts
features-title: Featured topics
# - displayed at the bottom
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!

# on all pages (and the first three you list display with greeting, if included)
social:
  #twitter: https://twitter.com/arkadianriver
  #github: https://github.com/arkadianriver
  #linkedin-square: https://linkedin.com/in/garyfaircloth
  facebook-official: https://www.facebook.com/ScubaVT/
  #google-plus-square: https://plus.google.com/u/0/+GaryFaircloth
  email: /contact/
  #flickr:
  instagram: https://www.instagram.com/scubaatvt/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []

# Club Officers Page
club_officers:
  - position: President
    name: Joey Griffiths
    major: Material Science Engineering
    cert:  IANTD Rescue Diver
    img: /images/scubavt/people/joey_square.jpg

  - position: Vice President and Dive Director
    name: Tyler Ruf
    major: Physics
    cert: IANTD Divemaster Candidate
    img: /images/scubavt/people/tyler_square.jpg

  - position: Treasurer
    name: Ashley Bond
    major:
    cert: IANTD Advanced Open Water
    img: /images/scubavt/people/ashley_square.jpg

  - position: Gear Officer
    name: Christine Ellis
    major:
    cert: IANTD Advanced Open Water
    img: /images/scubavt/people/christine_square.jpg

  - position: Gear Officer
    name: Clay Cunningham
    major: Computer Science
    cert: IAND Rescue Diver
    img: /images/scubavt/people/clay_square.jpg

  - position: Gear Officer
    name: Eli Carwile
    major: Building Construction Management
    cert: SDI Open Water
    img: /images/scubavt/people/eli_square.jpg

  - position: Webmaster
    name: <a href='http://chendaniely.github.io/'>Daniel Chen</a>
    major: Research Associate and PhD Student
    cert: IANTD Divemaster Candidate
    img: /images/scubavt/people/daniel_square.jpg

  - position: Secretary
    name: Sarah Wilson
    major:
    cert: IANTD Advanced Open Water
    img: /images/scubavt/people/sarah_square.jpg

# Instructors Page
instructors:
  - name: Mark Guenther
    img: /images/scubavt/people/mark_square.jpg
    agency: IANTD, PADI, SDI, TDI
    certs: Full Cave, Trimix
    teach: 
    blurb: >
      When he's not running his restaurant, <a href='https://www.facebook.com/PubGrubNRV/'>Pub Grub</a>,
      at the New River Valley Mall, he's diving.
      Mark's been involved with the club for <i>years</i>,
      and helps teach and supports us with many volunteer hours and gear rentals.
      There's nothing he won't do for us.
      He's pretty much got every certification, short of rebreather, and can teach almost as many.
      Drink of choice: Rumple Minze.

  - name: Chuk Horton
    img: /images/scubavt/people/chuck.jpg
    agency: IANTD, SDI
    certs: IANTD & SDI Open Water SCUBA Instructor
    teach: IANTD Diver 1st Aid/O2 Admin/AED , EANx , Open Water Open Water Nitrox 
    blurb: >
      Chuck is the Assistant Supervisor at the
      <a href='http://www.blacksburg.gov/departments/departments-l-z/parks-and-recreation/aquatic-center'>
      Blacksburg Aquatic Center</a>,
      where some of our confined pool sessions take place.
      He's an avid fútbol fan, and you can frequently find him around the local dive spots.
      One of the most jovial people you'll ever meet, he's also a great dive buddy.

  - name: Phillip Grambo
    img: /images/scubavt/people/phil_square.jpg
    agency: IANTD
    certs: TDI Sidemount, SDI Equipment Specialist
    teach: EANx, Open Water Open Water Nitrox
    blurb: >
      Señor Phil was the former president of the club,
      and is now an IANTD instructor helping the next round of students obtain his/her open water certification.
      But he's not your average instructor!
      Before gaining his instructor certification,
      Fill served as the club's divemaster for a year,
      and is currently helps visualize and inspect our tanks.
      He's also a graduate student in mechanical engineering at Tech.

  - name: Scott Sanders
    img: /images/scubavt/people/scott_square.jpg
    agency: IANTD, SDI, TDI
    certs: Everything
    teach: Everything
    blurb: >
      There wouldn't be a technical diving community in Blacksburg
      let alone a diving community without Scott.
      He is the founder of the local dive shop, <a href='http://techdivecenter.com/'>Tech Dive Center</a>,
      and currently the northeast sales representative for TUSA, Waterproof, Sea & Sea.
      He can pretty much teach you anything and everything you want to learn.

# Classes Offered
class:
  - Name: Class name
    ageny: class agency
    instructors: p1, p2
