# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Scuba Club at Virginia Tech
description: Exploring the seas
owner:
  name: Scuba Club at Virginia Tech
  email: scubaclub@vt.edu
  url: scubavt.github.io
first_published: 1996 # if migrating another site, the year of your first publish
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://arkadianriver.com" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Welcome!
  text: "We dive not to escape life, but for life not to escape us."
# - title for your blog's featured posts
features-title: Featured topics
# - displayed at the bottom
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!

# on all pages (and the first three you list display with greeting, if included)
social:
  #twitter: https://twitter.com/arkadianriver
  #github: https://github.com/arkadianriver
  #linkedin-square: https://linkedin.com/in/garyfaircloth
  facebook-official: https://www.facebook.com/ScubaVT/
  #google-plus-square: https://plus.google.com/u/0/+GaryFaircloth
  email: /contact/
  #flickr:
  instagram: https://www.instagram.com/scubaatvt/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []

# Club Officers Page
club_officers:
  - position: President
    name: Joey Griffiths
    major: Material Science Engineering
    cert:  IANTD Rescue Diver
    img: /images/scubavt/people/joey_square.jpg

  - position: Vice President and Dive Director
    name: Tyler Ruf
    major: Physics
    cert: IANTD Divemaster Candidate
    img: /images/scubavt/people/tyler_square.jpg

  - position: Treasurer
    name: Ashley Bond
    major:
    cert: IANTD Advanced Open Water
    img: /images/scubavt/people/ashley_square.jpg

  - position: Gear Officer
    name: Amanda Michel
    major:
    cert:
    img: /images/scubavt/people/amanda.jpg

  - position: Gear Officer
    name: Christine Ellis
    major:
    cert: IANTD Advanced Open Water
    img: /images/scubavt/people/christine_square.jpg

  - position: Gear Officer
    name: Clay Cunningham
    major: Computer Science
    cert: IAND Rescue Diver
    img: /images/scubavt/people/clay.jpg

  - position: Gear Officer
    name: Eli Carwile
    major: Building Construction Management
    cert: SDI Open Water
    img: /images/scubavt/people/eli_square.jpg

  - position: Webmaster
    name: Daniel Chen
    major: Research Associate and PhD Student
    cert: IANTD Divemaster Candidate
    img: /images/scubavt/people/daniel_square.jpg

  - position: Secretary
    name: Sarah Wilson
    major:
    cert: IANTD Advanced Open Water
    img: /images/scubavt/people/sarah_square.jpg

# Club Officers Page
instructors:
  - name: Mark Guenther
    img: /images/scubavt/people/mark_square.jpg
    certs: Full Cave, Trimix
    blurb: >
      Fully devoted to the sport of SCUBA,
      He also owns and runs <a href='https://www.facebook.com/PubGrubNRV/'>
      Pub Grub</a> at the New River Valley Mall.

  - name: Chuk Horton
    img: /images/scubavt/people/chuck.jpg
    certs: SDI Instructor
    blurb: >
      Chuck is a great guy.  He also works at the
      <a href='http://www.blacksburg.gov/departments/departments-l-z/parks-and-recreation/aquatic-center'>
      Blacksburg Aquatic Center</a>.

  - name: Phillip Grambo
    img: /images/scubavt/people/phil_square.jpg
    certs: IANTD Instructor
    blurb: >
      A former president of the club,
      Phill is now an IANTD instructor helping the next round obtain his/her
      open water certification.
      But he's not your average instructor!
      Before gaining his instructor certification,
      he served as the club's divemaster for a year,
      and is currently a graduate student in mechanical engineering at Tech.

  - name: Scott Sanders
    img: /images/scubavt/people/scott_square.jpg
    certs: Everything
    blurb: >
      There woudn't be a diving community in Blacksburg
      let alone a technical diving community without Scott.
      <a href='http://techdivecenter.com/'>Tech Dive Center</a>.