# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Scuba Club at Virginia Tech
description: Exploring the seas
owner:
  name: Scuba Club at Virginia Tech
  email: scubaclub@vt.edu
  url: scubavt.github.io
first_published: 1996 # if migrating another site, the year of your first publish
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://arkadianriver.com" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Welcome!
  text: "We dive not to escape life, but for life not to escape us."
# - title for your blog's featured posts
features-title: Featured topics
# - displayed at the bottom
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!

# on all pages (and the first three you list display with greeting, if included)
social:
  #twitter: https://twitter.com/arkadianriver
  #github: https://github.com/arkadianriver
  #linkedin-square: https://linkedin.com/in/garyfaircloth
  facebook-official: https://www.facebook.com/ScubaVT/
  #google-plus-square: https://plus.google.com/u/0/+GaryFaircloth
  email: /contact/
  #flickr:
  instagram: https://www.instagram.com/scubaatvt/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []

# Club Officers Page

  - position:
    name: 
    major:
    cert:

club_officers_settings:
  global_size_width: 200px
  global_size_height: 200px

club_officers:
  - position: President
    name: Joey Griffiths
    major: Material Science Engineering
    cert:  IANTD Rescue Diver
    img: /images/scibavt/people/joey.jpg

  - position: Vice President
    name: 
    major:
    cert:

  - position: Treasurer
    name: Ashley Bond
    major:
    cert: IANTD Advanced Open Water
    img: /images/scibavt/people/ashley.jpg

  - position: Dive Director
    name: Tyler Ruf
    major: Physics
    cert: IANTD Divemaster Candidate
    img: /images/scibavt/people/tyler.jpg

  - position: Gear Officer
    name: Amanda Michel
    major:
    cert:
    img: /images/scibavt/people/amanda.jpg

  - position: Gear Officer
    name: Christine Ellis
    major:
    cert: IANTD Advanced Open Water
    img: /images/scibavt/people/christine.jpg

  - position: Gear Officer
    name: Clay Cunningham
    major:
    cert:
    img: /images/scibavt/people/clay.jpg

  - position: Gear Officer
    name: Eli Carlyle
    major:
    cert:
    img: /images/scibavt/people/eli.jpg

  - position: Marketing
    name: 
    major:
    cert:

  - position: Historian
    name: 
    major:
    cert:

  - position: Fundraising
    name: 
    major:
    cert:

  - position: Divemaster
    name: 
    major:
    cert:

  - position: Instructor
    name: 
    major:
    cert:

  - position: Webmaster
    name: Daniel Chen,
    major: Research Associate and PhD Student
    cert: IANTD Divemaster Candidate
    img: /images/scibavt/people/daniel.jpg

  - position: Secretary
    name: Sarah Wilson
    major:
    cert: IANTD Advanced Open Water
    img: /images/scibavt/people/sarah.jpg
